services:
  tickets.api:
    image: tickets.api
    container_name: tickets.api
    build:
      context: .
      dockerfile: Tickets/Dockerfile
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_HTTP_PORTS=6000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tickets.dashboard:18889
    networks:
      - otel
  
  tickets.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: tickets.dashboard
    ports:
      - 18888:18888
    networks:
      - otel

networks:
  otel: